name: ci
on:
  push:
    paths-ignore: ["**.md"]
    branches: [ master ]
  pull_request:
    paths-ignore: ["**.md"]
    branches: [ master ]
jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
            toolchain: nightly
            components: clippy
      - run: cargo clippy
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
            toolchain: nightly
      - name: test core
        run: cargo test -p realm_core -v --no-fail-fast --features proxy
      - name: test binary
        run: cargo test -v --no-fail-fast
